//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Doc77Loader.Exchange1C {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Exchange1C77Soap", Namespace="http://stin-base.ru/")]
    public partial class Exchange1C77 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRepairStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFullRepairStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllRepairsByUserIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetClosedFlagVNaboreOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPriceListOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDocumentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFullTovarProdagiForWebOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFullTovarForWebOperationCompleted;
        
        private System.Threading.SendOrPostCallback NomenklaturaProdanaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsolidatedServiceReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReportZakazReglamentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Exchange1C77() {
            this.Url = global::Doc77Loader.Properties.Settings.Default.Doc77Loader_Exchange1C_Exchange1C77;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRepairStatusCompletedEventHandler GetRepairStatusCompleted;
        
        /// <remarks/>
        public event GetFullRepairStatusCompletedEventHandler GetFullRepairStatusCompleted;
        
        /// <remarks/>
        public event GetAllRepairsByUserIDCompletedEventHandler GetAllRepairsByUserIDCompleted;
        
        /// <remarks/>
        public event SetClosedFlagVNaboreCompletedEventHandler SetClosedFlagVNaboreCompleted;
        
        /// <remarks/>
        public event GetPriceListCompletedEventHandler GetPriceListCompleted;
        
        /// <remarks/>
        public event CreateDocumentsCompletedEventHandler CreateDocumentsCompleted;
        
        /// <remarks/>
        public event GetFullTovarProdagiForWebCompletedEventHandler GetFullTovarProdagiForWebCompleted;
        
        /// <remarks/>
        public event GetFullTovarForWebCompletedEventHandler GetFullTovarForWebCompleted;
        
        /// <remarks/>
        public event NomenklaturaProdanaCompletedEventHandler NomenklaturaProdanaCompleted;
        
        /// <remarks/>
        public event ConsolidatedServiceReportCompletedEventHandler ConsolidatedServiceReportCompleted;
        
        /// <remarks/>
        public event ReportZakazReglamentCompletedEventHandler ReportZakazReglamentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stin-base.ru/GetRepairStatus", RequestNamespace="http://stin-base.ru/", ResponseNamespace="http://stin-base.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRepairStatus(string KvNumber, int KvDate) {
            object[] results = this.Invoke("GetRepairStatus", new object[] {
                        KvNumber,
                        KvDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRepairStatusAsync(string KvNumber, int KvDate) {
            this.GetRepairStatusAsync(KvNumber, KvDate, null);
        }
        
        /// <remarks/>
        public void GetRepairStatusAsync(string KvNumber, int KvDate, object userState) {
            if ((this.GetRepairStatusOperationCompleted == null)) {
                this.GetRepairStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRepairStatusOperationCompleted);
            }
            this.InvokeAsync("GetRepairStatus", new object[] {
                        KvNumber,
                        KvDate}, this.GetRepairStatusOperationCompleted, userState);
        }
        
        private void OnGetRepairStatusOperationCompleted(object arg) {
            if ((this.GetRepairStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRepairStatusCompleted(this, new GetRepairStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stin-base.ru/GetFullRepairStatus", RequestNamespace="http://stin-base.ru/", ResponseNamespace="http://stin-base.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FullRepairStatus GetFullRepairStatus(string KvNumber, int KvDate) {
            object[] results = this.Invoke("GetFullRepairStatus", new object[] {
                        KvNumber,
                        KvDate});
            return ((FullRepairStatus)(results[0]));
        }
        
        /// <remarks/>
        public void GetFullRepairStatusAsync(string KvNumber, int KvDate) {
            this.GetFullRepairStatusAsync(KvNumber, KvDate, null);
        }
        
        /// <remarks/>
        public void GetFullRepairStatusAsync(string KvNumber, int KvDate, object userState) {
            if ((this.GetFullRepairStatusOperationCompleted == null)) {
                this.GetFullRepairStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFullRepairStatusOperationCompleted);
            }
            this.InvokeAsync("GetFullRepairStatus", new object[] {
                        KvNumber,
                        KvDate}, this.GetFullRepairStatusOperationCompleted, userState);
        }
        
        private void OnGetFullRepairStatusOperationCompleted(object arg) {
            if ((this.GetFullRepairStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFullRepairStatusCompleted(this, new GetFullRepairStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stin-base.ru/GetAllRepairsByUserID", RequestNamespace="http://stin-base.ru/", ResponseNamespace="http://stin-base.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RepairStatusArray GetAllRepairsByUserID(string UserID) {
            object[] results = this.Invoke("GetAllRepairsByUserID", new object[] {
                        UserID});
            return ((RepairStatusArray)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllRepairsByUserIDAsync(string UserID) {
            this.GetAllRepairsByUserIDAsync(UserID, null);
        }
        
        /// <remarks/>
        public void GetAllRepairsByUserIDAsync(string UserID, object userState) {
            if ((this.GetAllRepairsByUserIDOperationCompleted == null)) {
                this.GetAllRepairsByUserIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllRepairsByUserIDOperationCompleted);
            }
            this.InvokeAsync("GetAllRepairsByUserID", new object[] {
                        UserID}, this.GetAllRepairsByUserIDOperationCompleted, userState);
        }
        
        private void OnGetAllRepairsByUserIDOperationCompleted(object arg) {
            if ((this.GetAllRepairsByUserIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllRepairsByUserIDCompleted(this, new GetAllRepairsByUserIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stin-base.ru/SetClosedFlagVNabore", RequestNamespace="http://stin-base.ru/", ResponseNamespace="http://stin-base.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetClosedFlagVNabore(string iddoc, int closed, string worker, int f0, int f1, int f2) {
            object[] results = this.Invoke("SetClosedFlagVNabore", new object[] {
                        iddoc,
                        closed,
                        worker,
                        f0,
                        f1,
                        f2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetClosedFlagVNaboreAsync(string iddoc, int closed, string worker, int f0, int f1, int f2) {
            this.SetClosedFlagVNaboreAsync(iddoc, closed, worker, f0, f1, f2, null);
        }
        
        /// <remarks/>
        public void SetClosedFlagVNaboreAsync(string iddoc, int closed, string worker, int f0, int f1, int f2, object userState) {
            if ((this.SetClosedFlagVNaboreOperationCompleted == null)) {
                this.SetClosedFlagVNaboreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetClosedFlagVNaboreOperationCompleted);
            }
            this.InvokeAsync("SetClosedFlagVNabore", new object[] {
                        iddoc,
                        closed,
                        worker,
                        f0,
                        f1,
                        f2}, this.SetClosedFlagVNaboreOperationCompleted, userState);
        }
        
        private void OnSetClosedFlagVNaboreOperationCompleted(object arg) {
            if ((this.SetClosedFlagVNaboreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetClosedFlagVNaboreCompleted(this, new SetClosedFlagVNaboreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stin-base.ru/GetPriceList", RequestNamespace="http://stin-base.ru/", ResponseNamespace="http://stin-base.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PriceList GetPriceList(
                    string ext, 
                    string SkladListStr, 
                    string NomkListStr, 
                    int NomInSelect, 
                    string BrendListStr, 
                    int BrendInSelect, 
                    int harakter, 
                    int opt, 
                    int osob, 
                    int spec, 
                    int rozn, 
                    int zakaz, 
                    int ostPrice, 
                    int onlyOst, 
                    string CustomerListStr, 
                    int PeriodCode, 
                    string Address, 
                    int Top) {
            object[] results = this.Invoke("GetPriceList", new object[] {
                        ext,
                        SkladListStr,
                        NomkListStr,
                        NomInSelect,
                        BrendListStr,
                        BrendInSelect,
                        harakter,
                        opt,
                        osob,
                        spec,
                        rozn,
                        zakaz,
                        ostPrice,
                        onlyOst,
                        CustomerListStr,
                        PeriodCode,
                        Address,
                        Top});
            return ((PriceList)(results[0]));
        }
        
        /// <remarks/>
        public void GetPriceListAsync(
                    string ext, 
                    string SkladListStr, 
                    string NomkListStr, 
                    int NomInSelect, 
                    string BrendListStr, 
                    int BrendInSelect, 
                    int harakter, 
                    int opt, 
                    int osob, 
                    int spec, 
                    int rozn, 
                    int zakaz, 
                    int ostPrice, 
                    int onlyOst, 
                    string CustomerListStr, 
                    int PeriodCode, 
                    string Address, 
                    int Top) {
            this.GetPriceListAsync(ext, SkladListStr, NomkListStr, NomInSelect, BrendListStr, BrendInSelect, harakter, opt, osob, spec, rozn, zakaz, ostPrice, onlyOst, CustomerListStr, PeriodCode, Address, Top, null);
        }
        
        /// <remarks/>
        public void GetPriceListAsync(
                    string ext, 
                    string SkladListStr, 
                    string NomkListStr, 
                    int NomInSelect, 
                    string BrendListStr, 
                    int BrendInSelect, 
                    int harakter, 
                    int opt, 
                    int osob, 
                    int spec, 
                    int rozn, 
                    int zakaz, 
                    int ostPrice, 
                    int onlyOst, 
                    string CustomerListStr, 
                    int PeriodCode, 
                    string Address, 
                    int Top, 
                    object userState) {
            if ((this.GetPriceListOperationCompleted == null)) {
                this.GetPriceListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPriceListOperationCompleted);
            }
            this.InvokeAsync("GetPriceList", new object[] {
                        ext,
                        SkladListStr,
                        NomkListStr,
                        NomInSelect,
                        BrendListStr,
                        BrendInSelect,
                        harakter,
                        opt,
                        osob,
                        spec,
                        rozn,
                        zakaz,
                        ostPrice,
                        onlyOst,
                        CustomerListStr,
                        PeriodCode,
                        Address,
                        Top}, this.GetPriceListOperationCompleted, userState);
        }
        
        private void OnGetPriceListOperationCompleted(object arg) {
            if ((this.GetPriceListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPriceListCompleted(this, new GetPriceListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stin-base.ru/CreateDocuments", RequestNamespace="http://stin-base.ru/", ResponseNamespace="http://stin-base.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateDocuments([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] InputFile) {
            object[] results = this.Invoke("CreateDocuments", new object[] {
                        InputFile});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDocumentsAsync(byte[] InputFile) {
            this.CreateDocumentsAsync(InputFile, null);
        }
        
        /// <remarks/>
        public void CreateDocumentsAsync(byte[] InputFile, object userState) {
            if ((this.CreateDocumentsOperationCompleted == null)) {
                this.CreateDocumentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDocumentsOperationCompleted);
            }
            this.InvokeAsync("CreateDocuments", new object[] {
                        InputFile}, this.CreateDocumentsOperationCompleted, userState);
        }
        
        private void OnCreateDocumentsOperationCompleted(object arg) {
            if ((this.CreateDocumentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDocumentsCompleted(this, new CreateDocumentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stin-base.ru/GetFullTovarProdagiForWeb", RequestNamespace="http://stin-base.ru/", ResponseNamespace="http://stin-base.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PriceList GetFullTovarProdagiForWeb() {
            object[] results = this.Invoke("GetFullTovarProdagiForWeb", new object[0]);
            return ((PriceList)(results[0]));
        }
        
        /// <remarks/>
        public void GetFullTovarProdagiForWebAsync() {
            this.GetFullTovarProdagiForWebAsync(null);
        }
        
        /// <remarks/>
        public void GetFullTovarProdagiForWebAsync(object userState) {
            if ((this.GetFullTovarProdagiForWebOperationCompleted == null)) {
                this.GetFullTovarProdagiForWebOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFullTovarProdagiForWebOperationCompleted);
            }
            this.InvokeAsync("GetFullTovarProdagiForWeb", new object[0], this.GetFullTovarProdagiForWebOperationCompleted, userState);
        }
        
        private void OnGetFullTovarProdagiForWebOperationCompleted(object arg) {
            if ((this.GetFullTovarProdagiForWebCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFullTovarProdagiForWebCompleted(this, new GetFullTovarProdagiForWebCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stin-base.ru/GetFullTovarForWeb", RequestNamespace="http://stin-base.ru/", ResponseNamespace="http://stin-base.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PriceList GetFullTovarForWeb(bool IncludeProperties) {
            object[] results = this.Invoke("GetFullTovarForWeb", new object[] {
                        IncludeProperties});
            return ((PriceList)(results[0]));
        }
        
        /// <remarks/>
        public void GetFullTovarForWebAsync(bool IncludeProperties) {
            this.GetFullTovarForWebAsync(IncludeProperties, null);
        }
        
        /// <remarks/>
        public void GetFullTovarForWebAsync(bool IncludeProperties, object userState) {
            if ((this.GetFullTovarForWebOperationCompleted == null)) {
                this.GetFullTovarForWebOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFullTovarForWebOperationCompleted);
            }
            this.InvokeAsync("GetFullTovarForWeb", new object[] {
                        IncludeProperties}, this.GetFullTovarForWebOperationCompleted, userState);
        }
        
        private void OnGetFullTovarForWebOperationCompleted(object arg) {
            if ((this.GetFullTovarForWebCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFullTovarForWebCompleted(this, new GetFullTovarForWebCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stin-base.ru/NomenklaturaProdana", RequestNamespace="http://stin-base.ru/", ResponseNamespace="http://stin-base.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NomenklaturaProdanaReply NomenklaturaProdana(string CustomerCode) {
            object[] results = this.Invoke("NomenklaturaProdana", new object[] {
                        CustomerCode});
            return ((NomenklaturaProdanaReply)(results[0]));
        }
        
        /// <remarks/>
        public void NomenklaturaProdanaAsync(string CustomerCode) {
            this.NomenklaturaProdanaAsync(CustomerCode, null);
        }
        
        /// <remarks/>
        public void NomenklaturaProdanaAsync(string CustomerCode, object userState) {
            if ((this.NomenklaturaProdanaOperationCompleted == null)) {
                this.NomenklaturaProdanaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNomenklaturaProdanaOperationCompleted);
            }
            this.InvokeAsync("NomenklaturaProdana", new object[] {
                        CustomerCode}, this.NomenklaturaProdanaOperationCompleted, userState);
        }
        
        private void OnNomenklaturaProdanaOperationCompleted(object arg) {
            if ((this.NomenklaturaProdanaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NomenklaturaProdanaCompleted(this, new NomenklaturaProdanaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stin-base.ru/ConsolidatedServiceReport", RequestNamespace="http://stin-base.ru/", ResponseNamespace="http://stin-base.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RepairStatusArray ConsolidatedServiceReport(System.DateTime StartDate, string RemontType, string RemontVid, string Brend, string Master, string Avtor, string Postav) {
            object[] results = this.Invoke("ConsolidatedServiceReport", new object[] {
                        StartDate,
                        RemontType,
                        RemontVid,
                        Brend,
                        Master,
                        Avtor,
                        Postav});
            return ((RepairStatusArray)(results[0]));
        }
        
        /// <remarks/>
        public void ConsolidatedServiceReportAsync(System.DateTime StartDate, string RemontType, string RemontVid, string Brend, string Master, string Avtor, string Postav) {
            this.ConsolidatedServiceReportAsync(StartDate, RemontType, RemontVid, Brend, Master, Avtor, Postav, null);
        }
        
        /// <remarks/>
        public void ConsolidatedServiceReportAsync(System.DateTime StartDate, string RemontType, string RemontVid, string Brend, string Master, string Avtor, string Postav, object userState) {
            if ((this.ConsolidatedServiceReportOperationCompleted == null)) {
                this.ConsolidatedServiceReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsolidatedServiceReportOperationCompleted);
            }
            this.InvokeAsync("ConsolidatedServiceReport", new object[] {
                        StartDate,
                        RemontType,
                        RemontVid,
                        Brend,
                        Master,
                        Avtor,
                        Postav}, this.ConsolidatedServiceReportOperationCompleted, userState);
        }
        
        private void OnConsolidatedServiceReportOperationCompleted(object arg) {
            if ((this.ConsolidatedServiceReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsolidatedServiceReportCompleted(this, new ConsolidatedServiceReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stin-base.ru/ReportZakazReglament", RequestNamespace="http://stin-base.ru/", ResponseNamespace="http://stin-base.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ZakazReglamentReply ReportZakazReglament(
                    int IsMaster, 
                    string Extension, 
                    string StartDateStr, 
                    string EndDateStr, 
                    int fullInterf, 
                    int CostZak, 
                    int PrihRas, 
                    int Filial, 
                    int Upak, 
                    int MinOtgr, 
                    int Sertif, 
                    int flHarak, 
                    int flBrend, 
                    string NomenkSelect, 
                    int NomenkInclude, 
                    string ProizSelect, 
                    int ProizInclude, 
                    string FilialStr, 
                    string PpBrakStr, 
                    string BrakStr, 
                    string RozStr, 
                    string OtstoyStr, 
                    string AktStr, 
                    string SobNugdyStr, 
                    string PodarkyStr, 
                    string ProkatStr, 
                    string IlinStr) {
            object[] results = this.Invoke("ReportZakazReglament", new object[] {
                        IsMaster,
                        Extension,
                        StartDateStr,
                        EndDateStr,
                        fullInterf,
                        CostZak,
                        PrihRas,
                        Filial,
                        Upak,
                        MinOtgr,
                        Sertif,
                        flHarak,
                        flBrend,
                        NomenkSelect,
                        NomenkInclude,
                        ProizSelect,
                        ProizInclude,
                        FilialStr,
                        PpBrakStr,
                        BrakStr,
                        RozStr,
                        OtstoyStr,
                        AktStr,
                        SobNugdyStr,
                        PodarkyStr,
                        ProkatStr,
                        IlinStr});
            return ((ZakazReglamentReply)(results[0]));
        }
        
        /// <remarks/>
        public void ReportZakazReglamentAsync(
                    int IsMaster, 
                    string Extension, 
                    string StartDateStr, 
                    string EndDateStr, 
                    int fullInterf, 
                    int CostZak, 
                    int PrihRas, 
                    int Filial, 
                    int Upak, 
                    int MinOtgr, 
                    int Sertif, 
                    int flHarak, 
                    int flBrend, 
                    string NomenkSelect, 
                    int NomenkInclude, 
                    string ProizSelect, 
                    int ProizInclude, 
                    string FilialStr, 
                    string PpBrakStr, 
                    string BrakStr, 
                    string RozStr, 
                    string OtstoyStr, 
                    string AktStr, 
                    string SobNugdyStr, 
                    string PodarkyStr, 
                    string ProkatStr, 
                    string IlinStr) {
            this.ReportZakazReglamentAsync(IsMaster, Extension, StartDateStr, EndDateStr, fullInterf, CostZak, PrihRas, Filial, Upak, MinOtgr, Sertif, flHarak, flBrend, NomenkSelect, NomenkInclude, ProizSelect, ProizInclude, FilialStr, PpBrakStr, BrakStr, RozStr, OtstoyStr, AktStr, SobNugdyStr, PodarkyStr, ProkatStr, IlinStr, null);
        }
        
        /// <remarks/>
        public void ReportZakazReglamentAsync(
                    int IsMaster, 
                    string Extension, 
                    string StartDateStr, 
                    string EndDateStr, 
                    int fullInterf, 
                    int CostZak, 
                    int PrihRas, 
                    int Filial, 
                    int Upak, 
                    int MinOtgr, 
                    int Sertif, 
                    int flHarak, 
                    int flBrend, 
                    string NomenkSelect, 
                    int NomenkInclude, 
                    string ProizSelect, 
                    int ProizInclude, 
                    string FilialStr, 
                    string PpBrakStr, 
                    string BrakStr, 
                    string RozStr, 
                    string OtstoyStr, 
                    string AktStr, 
                    string SobNugdyStr, 
                    string PodarkyStr, 
                    string ProkatStr, 
                    string IlinStr, 
                    object userState) {
            if ((this.ReportZakazReglamentOperationCompleted == null)) {
                this.ReportZakazReglamentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReportZakazReglamentOperationCompleted);
            }
            this.InvokeAsync("ReportZakazReglament", new object[] {
                        IsMaster,
                        Extension,
                        StartDateStr,
                        EndDateStr,
                        fullInterf,
                        CostZak,
                        PrihRas,
                        Filial,
                        Upak,
                        MinOtgr,
                        Sertif,
                        flHarak,
                        flBrend,
                        NomenkSelect,
                        NomenkInclude,
                        ProizSelect,
                        ProizInclude,
                        FilialStr,
                        PpBrakStr,
                        BrakStr,
                        RozStr,
                        OtstoyStr,
                        AktStr,
                        SobNugdyStr,
                        PodarkyStr,
                        ProkatStr,
                        IlinStr}, this.ReportZakazReglamentOperationCompleted, userState);
        }
        
        private void OnReportZakazReglamentOperationCompleted(object arg) {
            if ((this.ReportZakazReglamentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReportZakazReglamentCompleted(this, new ReportZakazReglamentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stin-base.ru/")]
    public partial class FullRepairStatus {
        
        private ReplyState replyStateField;
        
        private CompleteRepairStatus completeRepairStatusField;
        
        /// <remarks/>
        public ReplyState ReplyState {
            get {
                return this.replyStateField;
            }
            set {
                this.replyStateField = value;
            }
        }
        
        /// <remarks/>
        public CompleteRepairStatus CompleteRepairStatus {
            get {
                return this.completeRepairStatusField;
            }
            set {
                this.completeRepairStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stin-base.ru/")]
    public partial class ReplyState {
        
        private string stateField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stin-base.ru/")]
    public partial class Results {
        
        private double prodanoAllSumField;
        
        private double prodanoAllMSumField;
        
        private double ostatokEndAllSumField;
        
        private double ostatokEndSvobodAllSumField;
        
        private double sumReglamentField;
        
        private double sumZakazField;
        
        /// <remarks/>
        public double ProdanoAllSum {
            get {
                return this.prodanoAllSumField;
            }
            set {
                this.prodanoAllSumField = value;
            }
        }
        
        /// <remarks/>
        public double ProdanoAllMSum {
            get {
                return this.prodanoAllMSumField;
            }
            set {
                this.prodanoAllMSumField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokEndAllSum {
            get {
                return this.ostatokEndAllSumField;
            }
            set {
                this.ostatokEndAllSumField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokEndSvobodAllSum {
            get {
                return this.ostatokEndSvobodAllSumField;
            }
            set {
                this.ostatokEndSvobodAllSumField = value;
            }
        }
        
        /// <remarks/>
        public double SumReglament {
            get {
                return this.sumReglamentField;
            }
            set {
                this.sumReglamentField = value;
            }
        }
        
        /// <remarks/>
        public double SumZakaz {
            get {
                return this.sumZakazField;
            }
            set {
                this.sumZakazField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stin-base.ru/")]
    public partial class SkladProperties {
        
        private string idField;
        
        private string codeField;
        
        private string nameField;
        
        private double ostatokField;
        
        private double prodagiField;
        
        private double nalFilField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public double Ostatok {
            get {
                return this.ostatokField;
            }
            set {
                this.ostatokField = value;
            }
        }
        
        /// <remarks/>
        public double prodagi {
            get {
                return this.prodagiField;
            }
            set {
                this.prodagiField = value;
            }
        }
        
        /// <remarks/>
        public double nalFil {
            get {
                return this.nalFilField;
            }
            set {
                this.nalFilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stin-base.ru/")]
    public partial class ZakazReglament {
        
        private string nomIDField;
        
        private string addressField;
        
        private string articulField;
        
        private string nomenklaturaField;
        
        private string brendField;
        
        private bool siteField;
        
        private string neZakupField;
        
        private double sebestoimField;
        
        private double spisstoimField;
        
        private double prodStoimField;
        
        private double costOptField;
        
        private double costOptSPField;
        
        private double costRoznField;
        
        private double costRoznSPField;
        
        private double costZakField;
        
        private double ostatokStartAllField;
        
        private double prihodAllField;
        
        private double rashodAllField;
        
        private double zamenaPlusField;
        
        private double zamenaMinusField;
        
        private double prodanoAllField;
        
        private double prodanoAllSumField;
        
        private double prodanoAllMField;
        
        private double prodanoAllMSumField;
        
        private double predZakazField;
        
        private double sprosField;
        
        private double dostavkaField;
        
        private double rezRaspredField;
        
        private double vNaboreField;
        
        private double vZayavkeField;
        
        private double uMasteraField;
        
        private double ostGarZaverField;
        
        private double oPrihodField;
        
        private double ostatokEndAllField;
        
        private double ostatokEndAllSumField;
        
        private double ostatokEndSvobodAllField;
        
        private double ostatokEndSvobodAllSumField;
        
        private double nalFilAllField;
        
        private double ostatokAnalogField;
        
        private double podZakazField;
        
        private double podZakazPlatnoField;
        
        private double zakazField;
        
        private double kolUpakField;
        
        private bool neNadoZakupField;
        
        private double reglamentCenterField;
        
        private double reglamentTZField;
        
        private double ostatokTZField;
        
        private double komissField;
        
        private double ostHranenieField;
        
        private double ostatokPPField;
        
        private double ostatokBrakMXField;
        
        private double ostatokRozField;
        
        private double ostatokOtstoyField;
        
        private double ostatokAktField;
        
        private double ostatokSobNugdyField;
        
        private double ostatokPodarkyField;
        
        private double ostatokProkatField;
        
        private double ostatokIlinField;
        
        private double kolPeremesField;
        
        private double kolPeremesOptField;
        
        private string certifField;
        
        private System.DateTime certifDateField;
        
        private double remontField;
        
        private double remontMField;
        
        private SkladProperties[] spField;
        
        /// <remarks/>
        public string NomID {
            get {
                return this.nomIDField;
            }
            set {
                this.nomIDField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Articul {
            get {
                return this.articulField;
            }
            set {
                this.articulField = value;
            }
        }
        
        /// <remarks/>
        public string Nomenklatura {
            get {
                return this.nomenklaturaField;
            }
            set {
                this.nomenklaturaField = value;
            }
        }
        
        /// <remarks/>
        public string Brend {
            get {
                return this.brendField;
            }
            set {
                this.brendField = value;
            }
        }
        
        /// <remarks/>
        public bool Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        public string NeZakup {
            get {
                return this.neZakupField;
            }
            set {
                this.neZakupField = value;
            }
        }
        
        /// <remarks/>
        public double Sebestoim {
            get {
                return this.sebestoimField;
            }
            set {
                this.sebestoimField = value;
            }
        }
        
        /// <remarks/>
        public double Spisstoim {
            get {
                return this.spisstoimField;
            }
            set {
                this.spisstoimField = value;
            }
        }
        
        /// <remarks/>
        public double ProdStoim {
            get {
                return this.prodStoimField;
            }
            set {
                this.prodStoimField = value;
            }
        }
        
        /// <remarks/>
        public double CostOpt {
            get {
                return this.costOptField;
            }
            set {
                this.costOptField = value;
            }
        }
        
        /// <remarks/>
        public double CostOptSP {
            get {
                return this.costOptSPField;
            }
            set {
                this.costOptSPField = value;
            }
        }
        
        /// <remarks/>
        public double CostRozn {
            get {
                return this.costRoznField;
            }
            set {
                this.costRoznField = value;
            }
        }
        
        /// <remarks/>
        public double CostRoznSP {
            get {
                return this.costRoznSPField;
            }
            set {
                this.costRoznSPField = value;
            }
        }
        
        /// <remarks/>
        public double CostZak {
            get {
                return this.costZakField;
            }
            set {
                this.costZakField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokStartAll {
            get {
                return this.ostatokStartAllField;
            }
            set {
                this.ostatokStartAllField = value;
            }
        }
        
        /// <remarks/>
        public double PrihodAll {
            get {
                return this.prihodAllField;
            }
            set {
                this.prihodAllField = value;
            }
        }
        
        /// <remarks/>
        public double RashodAll {
            get {
                return this.rashodAllField;
            }
            set {
                this.rashodAllField = value;
            }
        }
        
        /// <remarks/>
        public double ZamenaPlus {
            get {
                return this.zamenaPlusField;
            }
            set {
                this.zamenaPlusField = value;
            }
        }
        
        /// <remarks/>
        public double ZamenaMinus {
            get {
                return this.zamenaMinusField;
            }
            set {
                this.zamenaMinusField = value;
            }
        }
        
        /// <remarks/>
        public double ProdanoAll {
            get {
                return this.prodanoAllField;
            }
            set {
                this.prodanoAllField = value;
            }
        }
        
        /// <remarks/>
        public double ProdanoAllSum {
            get {
                return this.prodanoAllSumField;
            }
            set {
                this.prodanoAllSumField = value;
            }
        }
        
        /// <remarks/>
        public double ProdanoAllM {
            get {
                return this.prodanoAllMField;
            }
            set {
                this.prodanoAllMField = value;
            }
        }
        
        /// <remarks/>
        public double ProdanoAllMSum {
            get {
                return this.prodanoAllMSumField;
            }
            set {
                this.prodanoAllMSumField = value;
            }
        }
        
        /// <remarks/>
        public double PredZakaz {
            get {
                return this.predZakazField;
            }
            set {
                this.predZakazField = value;
            }
        }
        
        /// <remarks/>
        public double Spros {
            get {
                return this.sprosField;
            }
            set {
                this.sprosField = value;
            }
        }
        
        /// <remarks/>
        public double Dostavka {
            get {
                return this.dostavkaField;
            }
            set {
                this.dostavkaField = value;
            }
        }
        
        /// <remarks/>
        public double RezRaspred {
            get {
                return this.rezRaspredField;
            }
            set {
                this.rezRaspredField = value;
            }
        }
        
        /// <remarks/>
        public double VNabore {
            get {
                return this.vNaboreField;
            }
            set {
                this.vNaboreField = value;
            }
        }
        
        /// <remarks/>
        public double VZayavke {
            get {
                return this.vZayavkeField;
            }
            set {
                this.vZayavkeField = value;
            }
        }
        
        /// <remarks/>
        public double UMastera {
            get {
                return this.uMasteraField;
            }
            set {
                this.uMasteraField = value;
            }
        }
        
        /// <remarks/>
        public double OstGarZaver {
            get {
                return this.ostGarZaverField;
            }
            set {
                this.ostGarZaverField = value;
            }
        }
        
        /// <remarks/>
        public double OPrihod {
            get {
                return this.oPrihodField;
            }
            set {
                this.oPrihodField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokEndAll {
            get {
                return this.ostatokEndAllField;
            }
            set {
                this.ostatokEndAllField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokEndAllSum {
            get {
                return this.ostatokEndAllSumField;
            }
            set {
                this.ostatokEndAllSumField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokEndSvobodAll {
            get {
                return this.ostatokEndSvobodAllField;
            }
            set {
                this.ostatokEndSvobodAllField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokEndSvobodAllSum {
            get {
                return this.ostatokEndSvobodAllSumField;
            }
            set {
                this.ostatokEndSvobodAllSumField = value;
            }
        }
        
        /// <remarks/>
        public double NalFilAll {
            get {
                return this.nalFilAllField;
            }
            set {
                this.nalFilAllField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokAnalog {
            get {
                return this.ostatokAnalogField;
            }
            set {
                this.ostatokAnalogField = value;
            }
        }
        
        /// <remarks/>
        public double PodZakaz {
            get {
                return this.podZakazField;
            }
            set {
                this.podZakazField = value;
            }
        }
        
        /// <remarks/>
        public double PodZakazPlatno {
            get {
                return this.podZakazPlatnoField;
            }
            set {
                this.podZakazPlatnoField = value;
            }
        }
        
        /// <remarks/>
        public double zakaz {
            get {
                return this.zakazField;
            }
            set {
                this.zakazField = value;
            }
        }
        
        /// <remarks/>
        public double KolUpak {
            get {
                return this.kolUpakField;
            }
            set {
                this.kolUpakField = value;
            }
        }
        
        /// <remarks/>
        public bool NeNadoZakup {
            get {
                return this.neNadoZakupField;
            }
            set {
                this.neNadoZakupField = value;
            }
        }
        
        /// <remarks/>
        public double ReglamentCenter {
            get {
                return this.reglamentCenterField;
            }
            set {
                this.reglamentCenterField = value;
            }
        }
        
        /// <remarks/>
        public double ReglamentTZ {
            get {
                return this.reglamentTZField;
            }
            set {
                this.reglamentTZField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokTZ {
            get {
                return this.ostatokTZField;
            }
            set {
                this.ostatokTZField = value;
            }
        }
        
        /// <remarks/>
        public double Komiss {
            get {
                return this.komissField;
            }
            set {
                this.komissField = value;
            }
        }
        
        /// <remarks/>
        public double OstHranenie {
            get {
                return this.ostHranenieField;
            }
            set {
                this.ostHranenieField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokPP {
            get {
                return this.ostatokPPField;
            }
            set {
                this.ostatokPPField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokBrakMX {
            get {
                return this.ostatokBrakMXField;
            }
            set {
                this.ostatokBrakMXField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokRoz {
            get {
                return this.ostatokRozField;
            }
            set {
                this.ostatokRozField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokOtstoy {
            get {
                return this.ostatokOtstoyField;
            }
            set {
                this.ostatokOtstoyField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokAkt {
            get {
                return this.ostatokAktField;
            }
            set {
                this.ostatokAktField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokSobNugdy {
            get {
                return this.ostatokSobNugdyField;
            }
            set {
                this.ostatokSobNugdyField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokPodarky {
            get {
                return this.ostatokPodarkyField;
            }
            set {
                this.ostatokPodarkyField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokProkat {
            get {
                return this.ostatokProkatField;
            }
            set {
                this.ostatokProkatField = value;
            }
        }
        
        /// <remarks/>
        public double OstatokIlin {
            get {
                return this.ostatokIlinField;
            }
            set {
                this.ostatokIlinField = value;
            }
        }
        
        /// <remarks/>
        public double KolPeremes {
            get {
                return this.kolPeremesField;
            }
            set {
                this.kolPeremesField = value;
            }
        }
        
        /// <remarks/>
        public double KolPeremesOpt {
            get {
                return this.kolPeremesOptField;
            }
            set {
                this.kolPeremesOptField = value;
            }
        }
        
        /// <remarks/>
        public string Certif {
            get {
                return this.certifField;
            }
            set {
                this.certifField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CertifDate {
            get {
                return this.certifDateField;
            }
            set {
                this.certifDateField = value;
            }
        }
        
        /// <remarks/>
        public double Remont {
            get {
                return this.remontField;
            }
            set {
                this.remontField = value;
            }
        }
        
        /// <remarks/>
        public double RemontM {
            get {
                return this.remontMField;
            }
            set {
                this.remontMField = value;
            }
        }
        
        /// <remarks/>
        public SkladProperties[] sp {
            get {
                return this.spField;
            }
            set {
                this.spField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stin-base.ru/")]
    public partial class ZakazReglamentReply {
        
        private ReplyState replyStateField;
        
        private byte[] excelFileField;
        
        private ZakazReglament[] reportField;
        
        private Results resultField;
        
        /// <remarks/>
        public ReplyState ReplyState {
            get {
                return this.replyStateField;
            }
            set {
                this.replyStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExcelFile {
            get {
                return this.excelFileField;
            }
            set {
                this.excelFileField = value;
            }
        }
        
        /// <remarks/>
        public ZakazReglament[] Report {
            get {
                return this.reportField;
            }
            set {
                this.reportField = value;
            }
        }
        
        /// <remarks/>
        public Results Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stin-base.ru/")]
    public partial class CustTovar {
        
        private string custCodeField;
        
        private string idField;
        
        private string codeField;
        
        private string nameField;
        
        /// <remarks/>
        public string CustCode {
            get {
                return this.custCodeField;
            }
            set {
                this.custCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stin-base.ru/")]
    public partial class NomenklaturaProdanaReply {
        
        private ReplyState replyStateField;
        
        private CustTovar[] tovarsField;
        
        /// <remarks/>
        public ReplyState ReplyState {
            get {
                return this.replyStateField;
            }
            set {
                this.replyStateField = value;
            }
        }
        
        /// <remarks/>
        public CustTovar[] Tovars {
            get {
                return this.tovarsField;
            }
            set {
                this.tovarsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stin-base.ru/")]
    public partial class PriceList {
        
        private ReplyState replyStateField;
        
        private byte[] excelFileField;
        
        /// <remarks/>
        public ReplyState ReplyState {
            get {
                return this.replyStateField;
            }
            set {
                this.replyStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExcelFile {
            get {
                return this.excelFileField;
            }
            set {
                this.excelFileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stin-base.ru/")]
    public partial class RepairStatusArray {
        
        private ReplyState replyStateField;
        
        private int kolOpenRemontField;
        
        private int kolClosedRemontField;
        
        private int kolVydRemontField;
        
        private int kolNeVydRemontField;
        
        private decimal summaField;
        
        private decimal summaZField;
        
        private decimal summaRField;
        
        private decimal srSummaOneRemontField;
        
        private double srTimeOpenRemontField;
        
        private double srTimeClosedRemontField;
        
        private double srTimeVydRemontField;
        
        private int kolPerDocumentField;
        
        private int kolPriDocumentField;
        
        private decimal summaPerDocumentField;
        
        private decimal summaPriDocumentField;
        
        private int kolOtchOtpField;
        
        private decimal summaOtchOtpField;
        
        private decimal deltaField;
        
        private CompleteRepairStatus[] repairStatusesField;
        
        /// <remarks/>
        public ReplyState ReplyState {
            get {
                return this.replyStateField;
            }
            set {
                this.replyStateField = value;
            }
        }
        
        /// <remarks/>
        public int KolOpenRemont {
            get {
                return this.kolOpenRemontField;
            }
            set {
                this.kolOpenRemontField = value;
            }
        }
        
        /// <remarks/>
        public int KolClosedRemont {
            get {
                return this.kolClosedRemontField;
            }
            set {
                this.kolClosedRemontField = value;
            }
        }
        
        /// <remarks/>
        public int KolVydRemont {
            get {
                return this.kolVydRemontField;
            }
            set {
                this.kolVydRemontField = value;
            }
        }
        
        /// <remarks/>
        public int KolNeVydRemont {
            get {
                return this.kolNeVydRemontField;
            }
            set {
                this.kolNeVydRemontField = value;
            }
        }
        
        /// <remarks/>
        public decimal Summa {
            get {
                return this.summaField;
            }
            set {
                this.summaField = value;
            }
        }
        
        /// <remarks/>
        public decimal SummaZ {
            get {
                return this.summaZField;
            }
            set {
                this.summaZField = value;
            }
        }
        
        /// <remarks/>
        public decimal SummaR {
            get {
                return this.summaRField;
            }
            set {
                this.summaRField = value;
            }
        }
        
        /// <remarks/>
        public decimal SrSummaOneRemont {
            get {
                return this.srSummaOneRemontField;
            }
            set {
                this.srSummaOneRemontField = value;
            }
        }
        
        /// <remarks/>
        public double SrTimeOpenRemont {
            get {
                return this.srTimeOpenRemontField;
            }
            set {
                this.srTimeOpenRemontField = value;
            }
        }
        
        /// <remarks/>
        public double SrTimeClosedRemont {
            get {
                return this.srTimeClosedRemontField;
            }
            set {
                this.srTimeClosedRemontField = value;
            }
        }
        
        /// <remarks/>
        public double SrTimeVydRemont {
            get {
                return this.srTimeVydRemontField;
            }
            set {
                this.srTimeVydRemontField = value;
            }
        }
        
        /// <remarks/>
        public int KolPerDocument {
            get {
                return this.kolPerDocumentField;
            }
            set {
                this.kolPerDocumentField = value;
            }
        }
        
        /// <remarks/>
        public int KolPriDocument {
            get {
                return this.kolPriDocumentField;
            }
            set {
                this.kolPriDocumentField = value;
            }
        }
        
        /// <remarks/>
        public decimal SummaPerDocument {
            get {
                return this.summaPerDocumentField;
            }
            set {
                this.summaPerDocumentField = value;
            }
        }
        
        /// <remarks/>
        public decimal SummaPriDocument {
            get {
                return this.summaPriDocumentField;
            }
            set {
                this.summaPriDocumentField = value;
            }
        }
        
        /// <remarks/>
        public int KolOtchOtp {
            get {
                return this.kolOtchOtpField;
            }
            set {
                this.kolOtchOtpField = value;
            }
        }
        
        /// <remarks/>
        public decimal SummaOtchOtp {
            get {
                return this.summaOtchOtpField;
            }
            set {
                this.summaOtchOtpField = value;
            }
        }
        
        /// <remarks/>
        public decimal Delta {
            get {
                return this.deltaField;
            }
            set {
                this.deltaField = value;
            }
        }
        
        /// <remarks/>
        public CompleteRepairStatus[] RepairStatuses {
            get {
                return this.repairStatusesField;
            }
            set {
                this.repairStatusesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stin-base.ru/")]
    public partial class CompleteRepairStatus {
        
        private string kvitNumberField;
        
        private int kvitDateField;
        
        private string kontragentField;
        
        private string izdelieField;
        
        private string brendIDField;
        
        private string brendField;
        
        private string postavField;
        
        private string postavIDField;
        
        private string managerField;
        
        private string zavNumberField;
        
        private string repairTypeField;
        
        private System.DateTime datePriemaField;
        
        private string statusField;
        
        private string avtorField;
        
        private string avtorIDField;
        
        private string masterField;
        
        private string masterIDField;
        
        private string docZaverIdField;
        
        private System.DateTime dateZaverField;
        
        private decimal predvarSummaField;
        
        private decimal predvarSummaZField;
        
        private decimal predvarSummaRField;
        
        private decimal summaField;
        
        private decimal summaZField;
        
        private decimal summaRField;
        
        private System.DateTime dateVydField;
        
        private System.DateTime datePerField;
        
        private System.DateTime datePriField;
        
        private System.DateTime dateOtchOtpField;
        
        private System.DateTime dateOtchPriField;
        
        private System.DateTime dateGarOtchField;
        
        private decimal summaGarOtchField;
        
        /// <remarks/>
        public string KvitNumber {
            get {
                return this.kvitNumberField;
            }
            set {
                this.kvitNumberField = value;
            }
        }
        
        /// <remarks/>
        public int KvitDate {
            get {
                return this.kvitDateField;
            }
            set {
                this.kvitDateField = value;
            }
        }
        
        /// <remarks/>
        public string Kontragent {
            get {
                return this.kontragentField;
            }
            set {
                this.kontragentField = value;
            }
        }
        
        /// <remarks/>
        public string Izdelie {
            get {
                return this.izdelieField;
            }
            set {
                this.izdelieField = value;
            }
        }
        
        /// <remarks/>
        public string BrendID {
            get {
                return this.brendIDField;
            }
            set {
                this.brendIDField = value;
            }
        }
        
        /// <remarks/>
        public string Brend {
            get {
                return this.brendField;
            }
            set {
                this.brendField = value;
            }
        }
        
        /// <remarks/>
        public string Postav {
            get {
                return this.postavField;
            }
            set {
                this.postavField = value;
            }
        }
        
        /// <remarks/>
        public string PostavID {
            get {
                return this.postavIDField;
            }
            set {
                this.postavIDField = value;
            }
        }
        
        /// <remarks/>
        public string Manager {
            get {
                return this.managerField;
            }
            set {
                this.managerField = value;
            }
        }
        
        /// <remarks/>
        public string ZavNumber {
            get {
                return this.zavNumberField;
            }
            set {
                this.zavNumberField = value;
            }
        }
        
        /// <remarks/>
        public string RepairType {
            get {
                return this.repairTypeField;
            }
            set {
                this.repairTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DatePriema {
            get {
                return this.datePriemaField;
            }
            set {
                this.datePriemaField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Avtor {
            get {
                return this.avtorField;
            }
            set {
                this.avtorField = value;
            }
        }
        
        /// <remarks/>
        public string AvtorID {
            get {
                return this.avtorIDField;
            }
            set {
                this.avtorIDField = value;
            }
        }
        
        /// <remarks/>
        public string Master {
            get {
                return this.masterField;
            }
            set {
                this.masterField = value;
            }
        }
        
        /// <remarks/>
        public string MasterID {
            get {
                return this.masterIDField;
            }
            set {
                this.masterIDField = value;
            }
        }
        
        /// <remarks/>
        public string DocZaverId {
            get {
                return this.docZaverIdField;
            }
            set {
                this.docZaverIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateZaver {
            get {
                return this.dateZaverField;
            }
            set {
                this.dateZaverField = value;
            }
        }
        
        /// <remarks/>
        public decimal PredvarSumma {
            get {
                return this.predvarSummaField;
            }
            set {
                this.predvarSummaField = value;
            }
        }
        
        /// <remarks/>
        public decimal PredvarSummaZ {
            get {
                return this.predvarSummaZField;
            }
            set {
                this.predvarSummaZField = value;
            }
        }
        
        /// <remarks/>
        public decimal PredvarSummaR {
            get {
                return this.predvarSummaRField;
            }
            set {
                this.predvarSummaRField = value;
            }
        }
        
        /// <remarks/>
        public decimal Summa {
            get {
                return this.summaField;
            }
            set {
                this.summaField = value;
            }
        }
        
        /// <remarks/>
        public decimal SummaZ {
            get {
                return this.summaZField;
            }
            set {
                this.summaZField = value;
            }
        }
        
        /// <remarks/>
        public decimal SummaR {
            get {
                return this.summaRField;
            }
            set {
                this.summaRField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateVyd {
            get {
                return this.dateVydField;
            }
            set {
                this.dateVydField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DatePer {
            get {
                return this.datePerField;
            }
            set {
                this.datePerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DatePri {
            get {
                return this.datePriField;
            }
            set {
                this.datePriField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateOtchOtp {
            get {
                return this.dateOtchOtpField;
            }
            set {
                this.dateOtchOtpField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateOtchPri {
            get {
                return this.dateOtchPriField;
            }
            set {
                this.dateOtchPriField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateGarOtch {
            get {
                return this.dateGarOtchField;
            }
            set {
                this.dateGarOtchField = value;
            }
        }
        
        /// <remarks/>
        public decimal SummaGarOtch {
            get {
                return this.summaGarOtchField;
            }
            set {
                this.summaGarOtchField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetRepairStatusCompletedEventHandler(object sender, GetRepairStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRepairStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRepairStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetFullRepairStatusCompletedEventHandler(object sender, GetFullRepairStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFullRepairStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFullRepairStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FullRepairStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FullRepairStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAllRepairsByUserIDCompletedEventHandler(object sender, GetAllRepairsByUserIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllRepairsByUserIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllRepairsByUserIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RepairStatusArray Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RepairStatusArray)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SetClosedFlagVNaboreCompletedEventHandler(object sender, SetClosedFlagVNaboreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetClosedFlagVNaboreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetClosedFlagVNaboreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetPriceListCompletedEventHandler(object sender, GetPriceListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPriceListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPriceListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PriceList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PriceList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateDocumentsCompletedEventHandler(object sender, CreateDocumentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDocumentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDocumentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetFullTovarProdagiForWebCompletedEventHandler(object sender, GetFullTovarProdagiForWebCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFullTovarProdagiForWebCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFullTovarProdagiForWebCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PriceList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PriceList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetFullTovarForWebCompletedEventHandler(object sender, GetFullTovarForWebCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFullTovarForWebCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFullTovarForWebCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PriceList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PriceList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void NomenklaturaProdanaCompletedEventHandler(object sender, NomenklaturaProdanaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NomenklaturaProdanaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NomenklaturaProdanaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NomenklaturaProdanaReply Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NomenklaturaProdanaReply)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsolidatedServiceReportCompletedEventHandler(object sender, ConsolidatedServiceReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsolidatedServiceReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsolidatedServiceReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RepairStatusArray Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RepairStatusArray)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ReportZakazReglamentCompletedEventHandler(object sender, ReportZakazReglamentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReportZakazReglamentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReportZakazReglamentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZakazReglamentReply Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZakazReglamentReply)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591